[package]
name = "streamtools"
version = "0.4.0"
edition = "2021"
authors = ["extremeandy"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/extremeandy/streamtools"
description = "Additional stream combinators"
readme = "README.md"

[dependencies]
futures = "0.3.26"
pin-project-lite = "0.2.9"
parking_lot = "0.12.1"
tokio = { version = "1.25.0", optional = true, features = ["time"] }
tokio-stream = { version = "0.1.11", optional = true }

[dev-dependencies]
tokio = { version = "1.25.0", features = ["rt-multi-thread", "sync", "macros", "time"] }
tokio-stream = { version = "0.1.11", features = ["sync"] }
tokio-test = "0.4.2"

[features]
default = []
tokio-time = ["dep:tokio", "dep:tokio-stream"]